### PR TITLE
Fix null and RegExp literal values being allowed

### LINKED ISSUE #20: RegExp Expressions are allowed
image

😮

### LINKED ISSUE #30: null seems to crash the evaluator
A student figured out that the program
null;
is exiting the playground and leads to the Academy control room:

If I type

null;
in the playground and execute the program, the playground disappears.

 

And I paste the error message from Chrome console here:

TypeError: Cannot read property 'toString' of null
    at Object.t.toString (interop.js:88)
    at l (Repl.tsx:96)
    at t.Output.e (Repl.tsx:58)
    at beginWork (react-dom.production.min.js:136)
    at i (react-dom.production.min.js:175)
    at s (react-dom.production.min.js:175)
    at A (react-dom.production.min.js:181)
    at b (react-dom.production.min.js:180)
    at C (react-dom.production.min.js:180)
    at m (react-dom.production.min.js:179)
yr @ react-dom.production.min.js:150
utils.js:225 uncaught at  TypeError: Cannot read property 'toString' of null
    at Object.t.toString (https://sourceacademy.nus.edu.sg/static/js/main.b540f2aa.js:1:449154)
    at l (https://sourceacademy.nus.edu.sg/static/js/main.b540f2aa.js:53:388320)
    at t.Output.e (https://sourceacademy.nus.edu.sg/static/js/main.b540f2aa.js:53:387581)
    at beginWork (https://sourceacademy.nus.edu.sg/static/js/main.b540f2aa.js:4:1220991)
    at i (https://sourceacademy.nus.edu.sg/static/js/main.b540f2aa.js:4:1225586)
    at s (https://sourceacademy.nus.edu.sg/static/js/main.b540f2aa.js:4:1225865)
    at A (https://sourceacademy.nus.edu.sg/static/js/main.b540f2aa.js:4:1228810)
    at b (https://sourceacademy.nus.edu.sg/static/js/main.b540f2aa.js:4:1228353)
    at C (https://sourceacademy.nus.edu.sg/static/js/main.b540f2aa.js:4:1228190)
    at m (https://sourceacademy.nus.edu.sg/static/js/main.b540f2aa.js:4:1227569)
It seems that the playground does not catch a null and simply tries to toString() a null and crashes?

 

Hope this helps.

### PR DESCRIPTION
**Pull request by remo5000**
### Features
- Added a rule that only allows specified literal values (string, number, boolean)

### Issues fixed
- Fixes #20 
- Fixes #30

### CODE REVIEW

File: src/rules/noUnspecifiedLiteral.ts [hunk 1]
```diff
@@ -0,0 +1,48 @@
...
+  public explain() {
+    /** 
+     * A check is used for RegExp to ensure that only null and RegExp are caught.
+     * Any other unspecified literal value should not be caught.
+     */
+    const literal = this.node.value === null ? 'null' 
+      : this.node.value instanceof RegExp ? 'RegExp'
+      : ''
+    return (
+      `A literal '${literal}' value is not allowed. Only string, boolean, and number literal values are allowed.`
```
Comment (ningyuansg) [inline src/rules/noUnspecifiedLiteral.ts]: Prefer `'${literal} literals are not allowed'`, to be consistent with the other disallowed stuff, .e.g

> Line 1: Array expressions are not allowed

Comment (remo5000) [reply src/rules/noUnspecifiedLiteral.ts]: @ningyuansg Agreed. Updated!

**Comment by ningyuansg** [comment]
Thanks, please publish and we can update cadet-frontend.
