### PR TITLE
CSE Machine: Fix display bug when scanning out declarations

### LINKED ISSUE #1503: CSE machine: choice of ':' vs ':=' should be done when scanning out declarations and not when running asgn control instruction
Currently, all names are initialised with `:`, and asgn instructions are treated differently for `const` and `let` declarations.

When a `let` declaration is evaluated, the value is bound to the name. 
When a `const` declaration is evaluated, the same happens but there is additionally a `=` placed to the right of the `:`. 

Thus, in a program where a `const` declaration never gets evaluated but its block is reached, we have the situation where the environment diagram indicates `:` instead of `:=`:

image

(https://share.sourceacademy.nus.edu.sg/n1012)[https://share.sourceacademy.nus.edu.sg/n1012]

### PR DESCRIPTION
**Pull request by DiligentPenguinn**
### Description
This PR resolves #1503 . These are the changes implemented on the js-slang side
### Changes
- [x] Change initial values binded to keys from  `DECLARED_BUT_NOT_YET_ASSIGNED` to `UNASSIGNED_CONST` and `UNASSIGNED_LET`, which contains extra information about declaration type

### CODE REVIEW

File: src/cse-machine/__tests__/__snapshots__/cse-machine-errors.ts.snap [hunk 1]
```diff
@@ -78,8 +78,8 @@ Object {
 map = 5;",
   "displayResult": Array [],
   "numErrors": 1,
-  "parsedErrors": "Line 2, Column 0: Cannot assign new value to constant map.
-As map was declared as a constant, its value cannot be changed. You will have to declare a new variable.
+  "parsedErrors": "Line 2, Column 0: Name map not declared.
```
Comment (martin-henz) [inline src/cse-machine/__tests__/__snapshots__/cse-machine-errors.ts.snap:81]: The original error seems more appropriate here.

File: src/cse-machine/__tests__/__snapshots__/cse-machine-errors.ts.snap [hunk 2]
```diff
@@ -94,8 +94,8 @@ Object {
 undefined = 5;",
   "displayResult": Array [],
   "numErrors": 1,
-  "parsedErrors": "Line 2, Column 0: Cannot assign new value to constant undefined.
-As undefined was declared as a constant, its value cannot be changed. You will have to declare a new variable.
+  "parsedErrors": "Line 2, Column 0: Name undefined not declared.
```
Comment (martin-henz) [inline src/cse-machine/__tests__/__snapshots__/cse-machine-errors.ts.snap:97]: The name undefined is always declared in JavaScript and Source.

File: src/cse-machine/__tests__/__snapshots__/cse-machine-errors.ts.snap [hunk 3]
```diff
@@ -109,7 +109,7 @@ Object {
   "code": "map = 5;",
   "displayResult": Array [],
   "numErrors": 1,
-  "parsedErrors": "Line 1: Cannot assign new value to constant map.",
+  "parsedErrors": "Line 1: Name map not declared.",
```
Comment (martin-henz) [inline src/cse-machine/__tests__/__snapshots__/cse-machine-errors.ts.snap:112]: Original error seems more appropriate.

File: src/cse-machine/__tests__/__snapshots__/cse-machine-errors.ts.snap [hunk 4]
```diff
@@ -122,7 +122,7 @@ Object {
   "code": "undefined = 5;",
   "displayResult": Array [],
   "numErrors": 1,
-  "parsedErrors": "Line 1: Cannot assign new value to constant undefined.",
+  "parsedErrors": "Line 1: Name undefined not declared.",
```
Comment (martin-henz) [inline src/cse-machine/__tests__/__snapshots__/cse-machine-errors.ts.snap:125]: The name undefined is always declared in JavaScript and Source.

File: src/cse-machine/__tests__/__snapshots__/cse-machine-errors.ts.snap [hunk 5]
```diff
@@ -138,8 +138,8 @@ const f = x => g(x);
 f(1);",
   "displayResult": Array [],
   "numErrors": 1,
-  "parsedErrors": "Line 3, Column 15: Expected 0 arguments, but got 1.
-Try calling function g again, but with 0 arguments instead. Remember that arguments are separated by a ',' (comma).
+  "parsedErrors": "Line 2, Column 0: Redeclaring name g.
```
Comment (martin-henz) [inline src/cse-machine/__tests__/__snapshots__/cse-machine-errors.ts.snap:141]: original error seems more appropriate

File: src/cse-machine/__tests__/__snapshots__/cse-machine-errors.ts.snap [hunk 6]
```diff
@@ -155,7 +155,7 @@ const f = x => g(x);
 f(1);",
   "displayResult": Array [],
   "numErrors": 1,
-  "parsedErrors": "Line 2: Expected 0 arguments, but got 1.",
+  "parsedErrors": "Line 1: Redeclaring name g.",
```
Comment (martin-henz) [inline src/cse-machine/__tests__/__snapshots__/cse-machine-errors.ts.snap:158]: ditto

File: src/cse-machine/__tests__/__snapshots__/cse-machine-errors.ts.snap [hunk 7]
```diff
@@ -170,8 +170,8 @@ Object {
   f();",
   "displayResult": Array [],
   "numErrors": 1,
-  "parsedErrors": "Line 3, Column 2: Expected 1 arguments, but got 0.
-Try calling function f again, but with 1 argument instead. Remember that arguments are separated by a ',' (comma).
+  "parsedErrors": "Line 2, Column 2: Redeclaring name f.
```
Comment (martin-henz) [inline src/cse-machine/__tests__/__snapshots__/cse-machine-errors.ts.snap:173]: ditto

File: src/cse-machine/__tests__/__snapshots__/cse-machine-errors.ts.snap [hunk 8]
```diff
@@ -186,7 +186,7 @@ Object {
 f();",
   "displayResult": Array [],
   "numErrors": 1,
-  "parsedErrors": "Line 2: Expected 1 arguments, but got 0.",
+  "parsedErrors": "Line 1: Redeclaring name f.",
```
Comment (martin-henz) [inline src/cse-machine/__tests__/__snapshots__/cse-machine-errors.ts.snap:189]: ditto

File: src/cse-machine/__tests__/__snapshots__/cse-machine-errors.ts.snap [hunk 9]
```diff
@@ -201,8 +201,8 @@ Object {
   f(1, 2);",
   "displayResult": Array [],
   "numErrors": 1,
-  "parsedErrors": "Line 3, Column 2: Expected 1 arguments, but got 2.
-Try calling function f again, but with 1 argument instead. Remember that arguments are separated by a ',' (comma).
+  "parsedErrors": "Line 2, Column 2: Redeclaring name f.
```
Comment (martin-henz) [inline src/cse-machine/__tests__/__snapshots__/cse-machine-errors.ts.snap:204]: ditto

File: src/cse-machine/__tests__/__snapshots__/cse-machine-errors.ts.snap [hunk 10]
```diff
@@ -217,7 +217,7 @@ Object {
 f(1, 2);",
   "displayResult": Array [],
   "numErrors": 1,
-  "parsedErrors": "Line 2: Expected 1 arguments, but got 2.",
+  "parsedErrors": "Line 1: Redeclaring name f.",
```
Comment (martin-henz) [inline src/cse-machine/__tests__/__snapshots__/cse-machine-errors.ts.snap:220]: ditto

File: src/cse-machine/__tests__/__snapshots__/cse-machine-errors.ts.snap [hunk 11]
```diff
@@ -258,8 +258,8 @@ Object {
   f[0](1, 2);",
   "displayResult": Array [],
   "numErrors": 1,
-  "parsedErrors": "Line 3, Column 2: Expected 1 arguments, but got 2.
-Try calling function f[0] again, but with 1 argument instead. Remember that arguments are separated by a ',' (comma).
+  "parsedErrors": "Line 2, Column 2: Redeclaring name f.
```
Comment (martin-henz) [inline src/cse-machine/__tests__/__snapshots__/cse-machine-errors.ts.snap:261]: ditto

File: src/cse-machine/__tests__/__snapshots__/cse-machine-errors.ts.snap [hunk 12]
```diff
@@ -274,7 +274,7 @@ Object {
 f[0](1, 2);",
   "displayResult": Array [],
   "numErrors": 1,
-  "parsedErrors": "Line 2: Expected 1 arguments, but got 2.",
+  "parsedErrors": "Line 1: Redeclaring name f.",
```
Comment (martin-henz) [inline src/cse-machine/__tests__/__snapshots__/cse-machine-errors.ts.snap:277]: ditto

File: src/cse-machine/__tests__/__snapshots__/cse-machine-errors.ts.snap [hunk 13]
```diff
@@ -815,7 +815,7 @@ Object {
 }",
   "displayResult": Array [],
   "numErrors": 1,
-  "parsedErrors": "Line 3: Name a declared later in current scope but not yet assigned",
+  "parsedErrors": "Line 1: Redeclaring name a.",
```
Comment (martin-henz) [inline src/cse-machine/__tests__/__snapshots__/cse-machine-errors.ts.snap:818]: ditto

**Review by martin-henz — CHANGES_REQUESTED** [review]
Many test cases show regressions. Need to take another look.

**Review by martin-henz — APPROVED** [review]
all good now.
