### PR TITLE
Typed Source: Enable autocompletion for standard Source functions

### LINKED ISSUE #1529: Typed Source: Autocompletion for standard source functions does not work
Currently, code auto-completion for all of the standard library functions do not work when in Source Typed mode. The expected list of functions that should appear can be found in these links:

https://docs.sourceacademy.org/source_1/

## Expected Behaviour:
The auto-completion should show the built in functions when you start typing as follows:
Screenshot 2024-02-06 at 11 01 11 AM

## Actual Behaviour:
There is no auto-completion for the built in functions in Source Typed.
Screenshot 2024-02-06 at 11 01 31 AM

### PR DESCRIPTION
**Pull request by Zenkoh1**
This PR enables the autocompletion of the standard Source functions for the Typed Variant of Source. It does so by including the autocomplete documentation for Typed Source.

Closes #1529

### CODE REVIEW

File: scripts/updateAutocompleteDocs.js [hunk 1]
```diff
@@ -11,14 +11,18 @@ const SRC_FILENAME = "global.html"
...
+  'source_1_typed',
+  'source_2',
+  'source_2_typed',
+  'source_3',
+  'source_3_concurrent',
+  'source_3_non-det',
+  'source_3_typed',
+  'source_4',
+  'source_4_typed',
+  'External libraries'
```
Comment (RichDom2185) [inline scripts/updateAutocompleteDocs.js:25]: Seems like your editor is changing double quotes to single quotes automatically.... Hmm, I wonder why the CI allows this. Could you just change the necessary lines?

**Review by RichDom2185 — COMMENTED** [review]
Direction looks good! Just a minor nit below:

**Review by RichDom2185 — APPROVED** [review]
LGTM, thanks!
